### ISSUE TITLE
ImportError: cannot import name dequote

### ISSUE THREAD

**Issue by deshipu** [fusionbox/django-pyscss#19]
I just tried it with a pre-release version of pyScss 1.3.0.a1, and I'm getting this error:

    >>> import django_pyscss.compressor.DjangoScssFilter
    Traceback (most recent call last):
      File "<console>", line 1, in <module>
      File "/home/sheep/horizon/.venv/lib/python2.7/site-packages/django_pyscss/compressor.py", line 8, in <module>
         from django_pyscss.scss import DjangoScss
      File "/home/sheep/horizon/.venv/lib/python2.7/site-packages/django_pyscss/scss.py", line 9, in <module>
        from scss import (
    ImportError: cannot import name dequote

**Comment by rockymeza** [comment]
fixed by #31
